server:
  port: 8081
spring:
  application:
    name: flybook
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flybook?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 3000ms
jackson:
  default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: com.flybook.entity

logging:
  level:
    com.bytedance: debug
    org.springframework.web.socket: debug
    org.springframework.web.socket.server: debug
    javax.websocket: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: 0IjoxNzY0NDIxNjk3LCJleHAiOjE3NjUwMjY0OTd
  expire-time: 604800000

# 认证配置
auth:
  enabled: false

# 本地存储配置
storage:
  upload-path: D:/FlyBook/imgs/
  # 映射的访问前缀，即 http://localhost:8080/files/...
  access-prefix: /files/
  # 当前后端服务的地址，用于拼接完整URL
  domain: http://localhost:8081

# Snowflake ID 配置
flybook:
  snowflake:
    worker-id: 1
    datacenter-id: 1
  server:
    id: # 留空则自动生成
  mq:
    topic: flybook-message-push
    consumer-group: flybook-push-consumer-group

# RocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: flybook-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
